language: php

php:
  - 5.5

before_install:
- composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:dev-master
- composer install --dev
 
script:
- ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml tests/
 
after_script:
- php vendor/bin/coveralls -v