<?php

namespace EasyTransac\Entities;

/**
 * Represents the parameters for the "PaymentStatus" request.
 * This entity lets you check the status of a payment using different identifiers
 * (by TID, order ID, or request ID).
 */
class PaymentStatus extends Entity
{
    /**
     * Unique transaction identifier (TID).
     *
     * @var string|null
     * @map:Tid
     */
    protected $tid = null;

    /**
     * Order identifier associated with the payment.
     *
     * @var string|null
     * @map:OrderId
     */
    protected $orderId = null;

    /**
     * Request identifier (generated by the API when the transaction is created).
     *
     * @var string|null
     * @map:RequestId
     */
    protected $requestId = null;

    /**
     * Language to use for the response (e.g., 'fr', 'en').
     *
     * @var string|null
     * @map:Language
     */
    protected $language = null;

    /**
     * Sets the response language.
     *
     * @param string $value Language code (e.g., 'fr', 'en').
     * @return $this
     */
    public function setLanguage($value)
    {
        $this->language = $value;
        return $this;
    }

    /**
     * Sets the transaction identifier (TID).
     *
     * @param string $value Unique transaction identifier.
     * @return $this
     */
    public function setTid($value)
    {
        $this->tid = $value;
        return $this;
    }

    /**
     * Sets the order identifier.
     *
     * @param string $value Merchant-defined order ID.
     * @return $this
     */
    public function setOrderId($value)
    {
        $this->orderId = $value;
        return $this;
    }

    /**
     * Sets the API-generated request identifier.
     *
     * @param string $value Request ID.
     * @return $this
     */
    public function setRequestId($value)
    {
        $this->requestId = $value;
        return $this;
    }
}
