on: ["push", "pull_request"]
name: Coveralls

jobs:
  coveralls:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3
        with:
          path-to-lcov: ./coverage/lcov.xml
          git-branch: code_quality
          github-token: ${{ secrets.GITHUB_TOKEN }}