on: ["push", "pull_request"]
name: Coveralls

jobs:
  coveralls:
    runs-on: ubuntu-latest

    steps:
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ github.workspace }}/coverage/lcov.info