name: PHP Unit coverage badge

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: phpunit-coverage-badge
        uses: timkrase/phpunit-coverage-badge@v1.2.0
